### ISSUE TITLE
Thank You Participants

### ISSUE THREAD

**Issue by bennn** [syntax-objects/Summer2021#25]
Hello everyone! Thank you for contributing to the 2021 Syntax Parse Bee.

Your stickers are in the mail.

Over the next few weeks, I'll add your entries to the [`syntax-parse-example`](https://github.com/bennn/syntax-parse-example) repo. My plan is to open a pull request for each entry and give you 2 weeks to comment
on the PR.

Please let me know (here or by emailing `benjamin.l.greenman` at gmail) if one of the following applies to you:

 1. You **don't** want your macro in the other repo.
 2. You'd rather not receive any more GitHub notifications related to this bee.
 3. You want to open the PR yourself. (No need to comment if you've already opened a PR.)

For those interested in option 3, you can get started with these shell commands. Replace `MACRO-NAME` with the name of your macro (not the title of your GitHub issue; e.g., `while` and not `Basic while loop equipped with break`):

```
  raco pkg install --auto --clone syntax-parse-example
  raco syntax-parse-example --new MACRO-NAME
```

At any rate, enjoy the stickers & thanks again for the macros!

cc @Lazerbeak12345 @Fictitious-Rotor @hzafar @agj @xgqt @benknoble @AlexKnauth @sorawee @eutro @camoy @soegaard @Metaxal @dstorrs @countvajhula @shhyou

**Comment by Metaxal** [comment]
Do you mind if this issue is closed?
